language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_1a200b90ddab_key -iv $encrypted_1a200b90ddab_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d -md md5
- chmod +x deploy.sh
after_success:
- ./deploy.sh
